name: Testing Markdown

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
        with:
          node-version: "16"
          cache: "yarn"

      - name: Cache node_modules
        uses: actions/cache@v3.0.10
        id: cached-node_modules
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.github/workflows/testing.yml') }}

      - name: Install all yarn packages
        if: steps.cached-node_modules.outputs.cache-hit != 'true'
        run: |
          yarn --frozen-lockfile

      - name: Basic m2h/h2m tool testing
        env:
          ENV_FILE: testing/.env
        run: yarn test
