name: Testing Markdown

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: "14"
          cache: "yarn"

      - name: Cache node_modules
        uses: actions/cache@v2.1.7
        id: cached-node_modules
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.github/workflows/testing.yml') }}

      - name: Install all yarn packages
        if: steps.cached-node_modules.outputs.cache-hit != 'true'
        run: |
          yarn --frozen-lockfile

      - name: Basic m2h/h2m tool testing
        env:
          ENV_FILE: testing/.env
        run: |
          yarn md:test m2h markdown/tool/m2h --locale en-US
          diff -s testing/content/files/en-us/markdown/tool/m2h/index.html testing/content/files/en-us/markdown/tool/m2h/expected.html
          yarn md:test h2m markdown/tool/h2m --locale en-US
          diff -s testing/content/files/en-us/markdown/tool/h2m/index.md testing/content/files/en-us/markdown/tool/h2m/expected.md
